import type { Metadata } from "next";
import "./globals.css";
import { HeaderItem } from "./components/home/headerItem";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="">
        <header>
          <HeaderItem/>
        </header>
        <main>{children}</main>
        <footer>...</footer>
      </body>
    </html>
  );
}
